import Head from "next/head";

import styles from "../styles/Home.module.css";

export default function Home() {
	console.log(process.env.NEXT_PUBLIC_API_URI);
	return (
		<>
			<Head>
				<title>Asset Mgt System</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<h1>HOME</h1>
			</div>
		</>
	);
}
