import Head from "next/head";
import { useLoginForm } from "../customHooks/useLoginForm";
import styles from "../styles/Login.module.css";

export const getStaticProps = () => {
	return {
		props: {
			uri: process.env.NEXT_PUBLIC_API_URI,
		},
	};
};

export default function Login({ uri }) {
	// custom hook here
	const { handleChange, handleSubmit, values, errors } = useLoginForm(uri);
	return (
		<>
			<Head>
				<title>AMS - Login</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles.loginContainer}>
				{/* <h1>Login</h1> */}
				<form onSubmit={handleSubmit}>
					<input
						type="email"
						placeholder="Email Address"
						name="emailAddress"
						value={values.emailAddress}
						onChange={handleChange}
					/>
					{errors.emailAddress && <small>{errors.emailAddress}</small>}
					<input
						type="password"
						placeholder="Password"
						name="password"
						value={values.password}
						onChange={handleChange}
					/>
					{errors.password && <small>{errors.password}</small>}
					<button type="submit">Sign In</button>
					<a href="/register">Not yet registered? Sign up now!</a>
				</form>
			</div>
		</>
	);
}
