import Head from "next/head";
import { useState } from "react";

import styles from "../styles/Home.module.css";

export default function Register() {
	// useForm hook here

	const [firstName, setFirstName] = useState("");
	const [lastName, setLastName] = useState("");
	const [emailAddress, setEmailAddress] = useState("");
	const [password, setPassword] = useState("");
	const [confirm, setConfirm] = useState("");

	const handleSubmit = (e) => {
		e.preventDefault();
		console.log({
			firstName,
			lastName,
			emailAddress,
			password,
		});

		fetch("https://alvinacosta-asset-mgt.herokuapp.com/api/users/register", {
			method: "POST",
			headers: {
				"Content-Type": "application/json",
			},
			body: JSON.stringify({
				firstName,
				lastName,
				emailAddress,
				password,
			}),
		})
			.then((res) => res.json())
			.then((data) => {
				console.log(data);
			});

		setFirstName("");
		setLastName("");
		setEmailAddress("");
		setPassword("");
		setConfirm("");
	};

	return (
		<>
			<Head>
				<title>AMS - Register</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="main register container">
				<h1>Register</h1>
				<div className="form container">
					<form onSubmit={handleSubmit}>
						<input
							type="text"
							value={firstName}
							onChange={(e) => setFirstName(e.target.value)}
							placeholder="Enter your first name"
						/>
						<input
							type="text"
							value={lastName}
							onChange={(e) => setLastName(e.target.value)}
							placeholder="Enter your lastname"
						/>
						<input
							type="email"
							value={emailAddress}
							onChange={(e) => setEmailAddress(e.target.value)}
							placeholder="Enter your email address"
						/>
						<div>
							<input
								type="password"
								value={password}
								onChange={(e) => setPassword(e.target.value)}
								placeholder="Enter your new password"
							/>

							<input
								type="password"
								value={confirm}
								onChange={(e) => setConfirm(e.target.value)}
								placeholder="Confirm your new password"
							/>
						</div>
						<button type="submit">Register</button>
					</form>
				</div>
			</div>
		</>
	);
}
