import Head from "next/head";
import { useEffect, useState } from "react";
import { useRegisterForm } from "../customHooks/useRegisterForm";
import styles from "../styles/Register.module.css";

export default function Register() {
	// useForm hook here // all logic done there
	const { handleChange, handleSubmit, values, errors } = useRegisterForm();

	// no logic here but all the UI only for register.

	return (
		<>
			<Head>
				<title>AMS - Register</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className={styles.registerContainer}>
				{/* <h1>Register</h1> */}
				<form onSubmit={handleSubmit}>
					<input
						type="text"
						placeholder="Firstname"
						name="firstName"
						value={values.firstName}
						onChange={handleChange}
					/>
					{errors.firstName && <small>{errors.firstName}</small>}
					<input
						type="text"
						placeholder="Lastname"
						name="lastName"
						value={values.lastName}
						onChange={handleChange}
					/>
					{errors.lastName && <small>{errors.lastName}</small>}
					<input
						type="email"
						placeholder="Email Address"
						name="emailAddress"
						value={values.emailAddress}
						onChange={handleChange}
					/>
					{errors.emailAddress && <small>{errors.emailAddress}</small>}
					<div>
						<div className={styles.group}>
							<input
								type="password"
								placeholder="New Password"
								name="password"
								value={values.password}
								onChange={handleChange}
							/>
							{errors.password && <small>{errors.password}</small>}
						</div>
						<div className={styles.group}>
							<input
								type="password"
								placeholder="Confirm Password"
								name="confirm"
								value={values.confirm}
								onChange={handleChange}
							/>
							{errors.confirm && <small>{errors.confirm}</small>}
						</div>
					</div>
					<button type="submit">Sign Me Up</button>
				</form>
			</div>
		</>
	);
}
