import Head from "next/head";

import styles from "../styles/Home.module.css";

export default function Transactions() {
	return (
		<>
			<Head>
				<title>AMS - Transactions</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div>
				<h1>Transactions</h1>
			</div>
		</>
	);
}
